// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 Sacha Nelson

/**
 * Chrome user-profile decoration and clean-exit management.
 *
 * When launching a dedicated browser profile we want a recognizable name and
 * accent color in Chrome's profile picker.  Chrome stores this metadata in
 * two JSON files inside the user-data directory:
 *
 *   - `Local State`            (top-level profile registry)
 *   - `Default/Preferences`    (per-profile settings)
 *
 * This module reads, patches, and writes those files idempotently.
 *
 * Reference: Chromium source — `chrome/browser/profiles/profile_info_cache.cc`
 */

import fs from "node:fs";
import path from "node:path";
import { DEFAULT_BROWSER_COLOR, DEFAULT_BROWSER_PROFILE_NAME } from "../constants";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJson(fp: string): Record<string, unknown> | null {
  try {
    if (!fs.existsSync(fp)) return null;
    const parsed = JSON.parse(fs.readFileSync(fp, "utf-8")) as unknown;
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null;
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

function writeJson(fp: string, data: Record<string, unknown>) {
  fs.mkdirSync(path.dirname(fp), { recursive: true });
  fs.writeFileSync(fp, JSON.stringify(data, null, 2));
}

function deepSet(obj: Record<string, unknown>, keys: string[], value: unknown) {
  let node = obj;
  for (const key of keys.slice(0, -1)) {
    const next = node[key];
    if (typeof next !== "object" || next === null || Array.isArray(next)) {
      node[key] = {};
    }
    node = node[key] as Record<string, unknown>;
  }
  node[keys[keys.length - 1] ?? ""] = value;
}

/**
 * Chrome stores SkColor values as **signed 32-bit integers** with full alpha.
 * Convert a `#RRGGBB` hex string to that representation.
 */
function hexToSignedArgb(hex: string): number | null {
  const digits = hex.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]{6}$/.test(digits)) return null;
  const rgb = Number.parseInt(digits, 16);
  const unsigned = (0xff << 24) | rgb;
  return unsigned > 0x7fffffff ? unsigned - 0x1_0000_0000 : unsigned;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Return `true` when the profile at `userDataDir` already carries the desired
 * name and accent color so we can skip re-decoration.
 */
export function isProfileDecorated(userDataDir: string, desiredName: string, desiredColorHex: string): boolean {
  const colorInt = hexToSignedArgb(desiredColorHex);

  const localState = readJson(path.join(userDataDir, "Local State"));
  const profile = localState?.profile;
  const infoCache =
    typeof profile === "object" && profile !== null && !Array.isArray(profile)
      ? (profile as Record<string, unknown>).info_cache
      : null;
  const info =
    typeof infoCache === "object" &&
    infoCache !== null &&
    !Array.isArray(infoCache) &&
    typeof (infoCache as Record<string, unknown>).Default === "object" &&
    (infoCache as Record<string, unknown>).Default !== null &&
    !Array.isArray((infoCache as Record<string, unknown>).Default)
      ? ((infoCache as Record<string, unknown>).Default as Record<string, unknown>)
      : null;

  const prefs = readJson(path.join(userDataDir, "Default", "Preferences"));
  const browserTheme = (() => {
    const browser = prefs?.browser;
    const theme =
      typeof browser === "object" && browser !== null && !Array.isArray(browser)
        ? (browser as Record<string, unknown>).theme
        : null;
    return typeof theme === "object" && theme !== null && !Array.isArray(theme)
      ? (theme as Record<string, unknown>)
      : null;
  })();
  const autoTheme = (() => {
    const auto = prefs?.autogenerated;
    const theme =
      typeof auto === "object" && auto !== null && !Array.isArray(auto)
        ? (auto as Record<string, unknown>).theme
        : null;
    return typeof theme === "object" && theme !== null && !Array.isArray(theme)
      ? (theme as Record<string, unknown>)
      : null;
  })();

  const nameOk = typeof info?.name === "string" ? info.name === desiredName : true;
  if (colorInt == null) return nameOk;

  const seedOk = typeof info?.profile_color_seed === "number" ? info.profile_color_seed === colorInt : false;
  const prefOk =
    (typeof browserTheme?.user_color2 === "number" && browserTheme.user_color2 === colorInt) ||
    (typeof autoTheme?.color === "number" && autoTheme.color === colorInt);

  return nameOk && seedOk && prefOk;
}

/**
 * Best-effort profile decoration.  Sets profile name and accent color in both
 * `Local State` and `Default/Preferences`.
 */
export function decorateBrowserProfile(userDataDir: string, opts?: { name?: string; color?: string }) {
  const name = opts?.name ?? DEFAULT_BROWSER_PROFILE_NAME;
  const color = (opts?.color ?? DEFAULT_BROWSER_COLOR).toUpperCase();
  const colorInt = hexToSignedArgb(color);

  const localStatePath = path.join(userDataDir, "Local State");
  const prefsPath = path.join(userDataDir, "Default", "Preferences");

  // -- Local State --
  const ls = readJson(localStatePath) ?? {};
  const prefix = ["profile", "info_cache", "Default"];
  deepSet(ls, [...prefix, "name"], name);
  deepSet(ls, [...prefix, "shortcut_name"], name);
  deepSet(ls, [...prefix, "user_name"], name);
  deepSet(ls, [...prefix, "profile_color"], color);
  deepSet(ls, [...prefix, "user_color"], color);
  if (colorInt != null) {
    for (const key of [
      "profile_color_seed",
      "profile_highlight_color",
      "default_avatar_fill_color",
      "default_avatar_stroke_color",
    ]) {
      deepSet(ls, [...prefix, key], colorInt);
    }
  }
  writeJson(localStatePath, ls);

  // -- Preferences --
  const prefs = readJson(prefsPath) ?? {};
  deepSet(prefs, ["profile", "name"], name);
  deepSet(prefs, ["profile", "profile_color"], color);
  deepSet(prefs, ["profile", "user_color"], color);
  if (colorInt != null) {
    deepSet(prefs, ["autogenerated", "theme", "color"], colorInt);
    deepSet(prefs, ["browser", "theme", "user_color2"], colorInt);
  }
  writeJson(prefsPath, prefs);

  // Marker file so we know decoration was applied
  try {
    fs.writeFileSync(path.join(userDataDir, ".mastra-profile-decorated"), `${Date.now()}\n`, "utf-8");
  } catch {
    // best-effort
  }
}

/**
 * Clear the "crashed" / "dirty exit" flags so Chrome does not show the
 * session-restore bubble on next launch.
 */
export function ensureProfileCleanExit(userDataDir: string) {
  const prefsPath = path.join(userDataDir, "Default", "Preferences");
  const prefs = readJson(prefsPath) ?? {};
  deepSet(prefs, ["exit_type"], "Normal");
  deepSet(prefs, ["exited_cleanly"], true);
  writeJson(prefsPath, prefs);
}
